### ISSUE TITLE
https://dart.dev/null-safety/migration-guide

### ISSUE THREAD

**Issue by venkata-reddy-dev** [Benjith/NumberToWords#2]

**Comment by venkata-reddy-dev** [comment]
@Benjith here is [pull](https://github.com/Benjith/NumberToWords/pull/4) request

**Comment by lavahasif** [comment]
Please use  this  for null-safety
<pre class="highlight"><code><span class="na">dependencies</span><span class="pi">:</span>
  <span class="na">number_to_words:</span><span class="pi">:</span>
    <span class="na">git</span><span class="pi">:</span>
      <span class="na">url</span><span class="pi">:</span> <span class="s">git://github.com/RR-Reddy/NumberToWords.git</span>
      <span class="na">ref</span><span class="pi">:</span> <span class="s">master</span>
</code></pre>
